### ISSUE TITLE
Unexpected error after a long (>15.000) steps.

### ISSUE THREAD

**Issue by mmorini** [mmorini/language-abm#1]
OF expected input to be a turtle agentset or turtle but got NOBODY instead.
error while observer running OF
  called by procedure WORD-DISTANCE (/home/matteo/WORK/PhD/SUMMERSCHOOL/CSSS_SFI/projects/language-ABM/language-abm/src-netlogo/vocabulary.nls)
  called by (command task from: procedure LANGUAGE-DIVERSITY (/home/matteo/WORK/PhD/SUMMERSCHOOL/CSSS_SFI/projects/language-ABM/language-abm/src-netlogo/indicators.nls))
  called by procedure LANGUAGE-DIVERSITY (/home/matteo/WORK/PhD/SUMMERSCHOOL/CSSS_SFI/projects/language-ABM/language-abm/src-netlogo/indicators.nls)
  called by plot 'diversity' pen 'default' update code
  called by procedure GO (/home/matteo/WORK/PhD/SUMMERSCHOOL/CSSS_SFI/projects/language-ABM/language-abm/src-netlogo/main.nls)
  called by Button 'go'

**Comment by JusteRaimbault** [comment]
it should be due to a dead word that has not been erased from the mapping table (netlogo tables are shitty and do not accept agents as keys, so the mapping is on string representations) ; the invariant (table keys == alive words) was supposed to be conserved, I investigate where I may have forgotten it.

**Comment by mmorini** [comment]
Yep, sorry for finding out a way to create extra work... thanks!

Sent from my tricorder

-------- Original Message --------

**Comment by JusteRaimbault** [comment]
found a discrepancy between spoken-words and mapping keys already at setup, investigating this.

**Comment by JusteRaimbault** [comment]
fixed using static constructor (dirty hashconsing mimic) for new spoken-words. close.
